cachecloud-web/src/main/java/com/sohu/cache/entity/AppDailyData.java
package com.sohu.cache.entity;

import com.sohu.cache.web.vo.AppDetailVO;
import lombok.Data;
import org.apache.commons.collections.MapUtils;

import java.util.Date;
import java.util.Map;

/**
 * 应用日报数据
 *
 * @author leifu
 */
@Data
public class AppDailyData {

    /**
     * 应用id
     */
    private long appId;

    /**
     * 开始日期
     */
    private Date startDate;

    /**
     * 结束日期
     */
    private Date endDate;

    /**
     * 日期
     */
    private Date date;

    /**
     * bigkey次数
     */
    private long bigKeyTimes;

    /**
     * bigkey信息
     */
    private String bigKeyInfo;

    /**
     * 慢查询次数
     */
    private long slowLogCount;

    /**
     * 延迟事件个数
     */
    private long latencyCount;

    /**
     * 客户端异常个数
     */
    private long clientExceptionCount;
    /**
     * 累计命令调用次数
     */
    private long clientCmdCount;
    /**
     * 平均命令调用耗时
     */
    private double clientAvgCmdCost;
    /**
     * 累计连接异常事件次数
     */
    private long clientConnExpCount;
    /**
     * 平均连接异常事件耗时
     */
    private double clientAvgConnExpCost;
    /**
     * 累计命令超时事件次数
     */
    private long clientCmdExpCount;
    /**
     * 平均命令超时事件耗时
     */
    private double clientAvgCmdExpCost;

    /**
     * 每分钟最大客户端连接数
     */
    private long maxMinuteClientCount;

    /**
     * 每分钟平均客户端连接数
     */
    private long avgMinuteClientCount;

    /**
     * 每分钟最大命令数
     */
    private long maxMinuteCommandCount;

    /**
     * 每分钟平均命令数
     */
    private long avgMinuteCommandCount;

    /**
     * 平均命中率
     */
    private double avgHitRatio;

    /**
     * 每分钟最小命中率
     */
    private double minMinuteHitRatio;

    /**
     * 每分钟最大命中率
     */
    private double maxMinuteHitRatio;

    /**
     * 平均内存使用量
     */
    private long avgUsedMemory;

    /**
     * 最大内存使用量
     */
    private long maxUsedMemory;

    /**
     * 过期键个数
     */
    private long expiredKeysCount;

    /**
     * 剔除键个数
     */
    private long evictedKeysCount;

    /**
     * 每分钟平均网络input量
     */
    private double avgMinuteNetInputByte;

    /**
     * 每分钟最大网络input量
     */
    private double maxMinuteNetInputByte;

    /**
     * 每分钟平均网络output量
     */
    private double avgMinuteNetOutputByte;

    /**
     * 每分钟最大网络output量
     */
    private double maxMinuteNetOutputByte;

    /**
     * 键个数平均值
     */
    private long avgObjectSize;

    /**
     * 键个数最大值
     */
    private long maxObjectSize;

    /**
     * 值分布
     */
    private Map<String, Long> valueSizeDistributeCountMap;

    /**
     * 应用详情
     */
    private AppDetailVO appDetailVO;

    public String getValueSizeDistributeCountDesc() {
        if (MapUtils.isEmpty(valueSizeDistributeCountMap)) {
            return "无";
        }
        StringBuffer desc = new StringBuffer();
        for (Map.Entry<String, Long> entry : valueSizeDistributeCountMap.entrySet()) {
            desc.append(entry.getKey()).append(":").append(entry.getValue()).append("次<br/>");
        }
        return desc.toString();
    }

    public String getValueSizeDistributeCountDescHtml() {
        return bigKeyInfo.replace("\n", "<br/>").replace(":", ":\t");
    }
}

cachecloud-web/src/main/java/com/sohu/cache/entity/AppDesc.java
package com.sohu.cache.entity;

import com.sohu.cache.constant.AppDescEnum;
import com.sohu.cache.constant.AppDescEnum.AppImportantLevel;
import com.sohu.cache.constant.AppStatusEnum;
import com.sohu.cache.util.ConstUtils;
import com.sohu.cache.web.enums.AppTypeEnum;
import lombok.Data;
import org.apache.commons.lang.StringUtils;
import redis.clients.jedis.util.AuthUtil;

import java.io.Serializable;
import java.util.Date;
import java.util.concurrent.TimeUnit;

/**
 * 应用的信息
 * User: lingguo
 */
@Data
public class AppDesc implements Serializable {
    private static final long serialVersionUID = -3507970915810652761L;

    /**
     * 应用id
     */
    private long appId;

    /**
     * 应用秘钥
     */
    private String appKey;

    /**
     * 应用名称
     */
    private String name;

    /**
     * 用户id
     */
    private long userId;

    /**
     * 应用状态, 0未分配，1是申请了未审批，2是审批并发布, 3应用下线 4 驳回
     */
    private int status;

    /**
     * 应用描述
     */
    private String intro;

    /**
     * 创建时间
     */
    private Date createTime;

    /**
     * 申请通过的时间
     */
    private Date passedTime;

    /**
     * 类型
     */
    private int type;

    /**
     * 类型描述
     */
    private String typeDesc;

    /**
     * 负责人，用户id，逗号分隔
     */
    private String officer;

    /**
     * 版本号
     */
    private int verId;

    /**
     * 是否测试：1是0否
     */
    private int isTest;

    /**
     * 是否有后端数据源: 1是0否
     */
    private int hasBackStore;

    /**
     * 是否需要持久化: 1是0否
     */
    private int needPersistence;

    /**
     * 预估qps
     */
    private int forecaseQps;

    /**
     * 是否需要热备: 1是0否
     */
    private int needHotBackUp;

    /**
     * 预估条目数
     */
    private int forecastObjNum;

    /**
     * 内存报警阀值
     */
    private int memAlertValue;

    /**
     * 客户端连接数报警阀值
     */
    private int clientConnAlertValue;

    /**
     * 客户端命中率报警阀值 0:默认不监控
     */
    private int hitPrecentAlertValue;

    /**
     * 客户端是否接入 全局监控
     */
    private int isAccessMonitor;

    /**
     * 客户端机器机房
     */
    private String clientMachineRoom;

    /**
     * redis密码
     */
    private String pkey;

    /**
     * 重要度，默认重要
     */
    private int importantLevel = AppImportantLevel.IMPORTANT.getValue();

    /**
     * Redis版本id,名称
     */
    private int versionId;
    private String versionName;

    /**
     * Redis小版本是否可以升级 0:最新版本  1:可升小版本
     */
    private int isVersionUpgrade = 0;

    public String getAuthPassword() {
        String authPassword = appId + AuthUtil.SPLIT_KEY;
        if (StringUtils.isNotBlank(pkey)) {
            authPassword += getPasswordMd5();
        }
        return authPassword;
    }

    public String getPasswordMd5() {
        if (StringUtils.isNotBlank(pkey)) {
            return AuthUtil.getAppIdMD5(pkey);
        }
        return null;
    }

    /**
     * 应用运行天数
     */
    public int getAppRunDays() {
        if (createTime == null) {
            return -1;
        }
        Date now = new Date();
        long diff = now.getTime() - createTime.getTime();
        return (int) (diff / TimeUnit.DAYS.toMillis(1));
    }

    public String getTypeDesc() {
        if (type == ConstUtils.CACHE_TYPE_REDIS_CLUSTER) {
            return "redis-cluster";
        } else if (type == ConstUtils.CACHE_REDIS_SENTINEL) {
            return "redis-sentinel";
        } else if (type == ConstUtils.CACHE_REDIS_STANDALONE) {
            return "redis-standalone";
        } else if (type == ConstUtils.CACHE_REDIS_TWEMPROXY) {
            return "redis-twemproxy";
        } else if (type == ConstUtils.CACHE_PIKA_SENTINEL) {
            return "pika-sentinel";
        } else if (type == ConstUtils.CACHE_PIKA_TWEMPROXY) {
            return "pika-twemproxy";
        }
        return "";
    }

    public String getStatusDesc() {
        AppStatusEnum appStatusEnum = AppStatusEnum.getByStatus(status);
        if (appStatusEnum != null) {
            return appStatusEnum.getInfo();
        }
        return "";
    }

    /**
     * 是否上线
     *
     * @return
     */
    public boolean isOnline() {
        return status == AppStatusEnum.STATUS_PUBLISHED.getStatus();
    }

    /**
     * 是否下线
     *
     * @return
     */
    public boolean isOffline() {
        return status == AppStatusEnum.STATUS_OFFLINE.getStatus();
    }

    /**
     * 是否是测试
     *
     * @return
     */
    public boolean isTestOk() {
        return isTest == AppDescEnum.AppTest.IS_TEST.getValue();
    }

    /**
     * 非常重要
     *
     * @return
     */
    public boolean isVeryImportant() {
        return importantLevel == AppDescEnum.AppImportantLevel.VERY_IMPORTANT.getValue();
    }

    /**
     * 超级重要
     *
     * @return
     */
    public boolean isSuperImportant() {
        return importantLevel == AppDescEnum.AppImportantLevel.SUPER_IMPORTANT.getValue();
    }

    /**
     * memcache相关
     *
     * @return
     */
    public boolean isMemcached() {
        return AppTypeEnum.MEMCACHED.getType() == type;
    }

    public Date getCreateTime() {
        if (createTime != null) {
            return (Date) createTime.clone();
        }
        return null;
    }

    public void setCreateTime(Date createTime) {
        this.createTime = (Date) createTime.clone();
    }

    public Date getPassedTime() {
        if (passedTime != null) {
            return (Date) passedTime.clone();
        }
        return null;
    }

    public void setPassedTime(Date passedTime) {
        this.passedTime = (Date) passedTime.clone();
    }
}

cachecloud-web/src/main/java/com/sohu/cache/entity/AppStats.java
package com.sohu.cache.entity;

import lombok.Data;
import org.apache.commons.lang.math.NumberUtils;

import java.text.DecimalFormat;
import java.text.NumberFormat;
import java.util.Date;
import java.util.List;

/**
 * Created by yijunzhang on 14-6-9.
 */
@Data
public class AppStats {

    /**
     * 应用id
     */
    private long appId;

    /**
     * 收集时间:格式yyyyMMddHHmm/yyyyMMdd/yyyyMMddHH
     */
    private long collectTime;

    /**
     * 命中数量
     */
    private long hits;

    /**
     * 未命中数量
     */
    private long misses;

    /**
     * 命令执行次数
     */
    private long commandCount;

    /**
     * 内存占用
     */
    private long usedMemory;

    /**
     * 物理内存占用
     */
    private long usedMemoryRss;

    /**
     * 过期key数量
     */
    private long expiredKeys;

    /**
     * 驱逐key数量
     */
    private long evictedKeys;

    /**
     * 网络输入字节
     */
    private long netInputByte;

    /**
     * 网络输出字节
     */
    private long netOutputByte;

    /**
     * 客户端连接数
     */
    private int connectedClients;

    /**
     * 存储对象数
     */
    private long objectSize;

    /**
     * 进程系统态消耗(单位:秒)
     */
    private long cpuSys;
    /**
     * 进程用户态消耗(单位:秒)
     */
    private long cpuUser;

    /**
     * 子进程内核态消耗(单位:秒)
     */
    private long cpuSysChildren;
    /**
     * 子进程用户态消耗(单位:秒)
     */
    private long cpuUserChildren;

    /**
     * 累加的实例数
     */
    private int accumulation;

    /**
     * 创建时间
     */
    private Date createTime;
    /**
     * 修改时间
     */
    private Date modifyTime;

    /**
     * 命令统计集合
     */
    private List<AppCommandStats> commandStatsList;

    /**
     * 命中率
     *
     * @return
     */
    public long getHitPercent() {
        long total = hits + misses;
        if (total == 0) {
            return 0;
        } else {
            NumberFormat formatter = new DecimalFormat("0");
            return NumberUtils.toLong(formatter.format(hits * 100.0 / total));
        }
    }

    public Date getCreateTime() {
        return (Date) createTime.clone();
    }

    public void setCreateTime(Date createTime) {
        this.createTime = (Date) createTime.clone();
    }

    public Date getModifyTime() {
        return (Date) modifyTime.clone();
    }

    public void setModifyTime(Date modifyTime) {
        this.modifyTime = (Date) modifyTime.clone();
    }

}

cachecloud-web/src/main/webapp/WEB-INF/jsp/app/appClientList.jsp
<%@ page contentType="text/html;charset=UTF-8" language="java" %>
<%@ include file="/WEB-INF/jsp/manage/commons/taglibs.jsp" %>

<div class="container">
    <br/>
    <div class="row">
        <div class="col-md-12">
            <div class="page-header">
                <h4>应用连接信息</h4>
            </div>
            <div class="page-header">
                <h5>
                    <form method="post" action="/admin/app/index?appId=${appDesc.appId}&tabTag=app_clientList" id="conditionFrom">
                        <input type="radio" value="0" <c:if test="${condition == 0}">checked="checked"</c:if>
                               onchange="changeCondition(this.value)"/> 应用客户端
                        <input type="radio" value="1" <c:if test="${condition == 1}">checked="checked"</c:if>
                               onchange="changeCondition(this.value)"/> cc客户端
                        <input type="radio" value="2" <c:if test="${condition == 2}">checked="checked"</c:if>
                               onchange="changeCondition(this.value)"/> redis客户端
                        <input type="radio" value="3" <c:if test="${condition == 3}">checked="checked"</c:if>
                               onchange="changeCondition(this.value)"/> 所有客户端
                        <input type="hidden" id="condition" name="condition" value="${condition}">
                    </form>
                </h5>
            </div>
            <table class="table table-striped table-hover">
                <thead>
                <tr>
                    <td>序号</td>
                    <td>客户端ip</td>
                    <td>总连接数</td>
                    <td>客户端类型</td>
                    <td>实例详细</td>
                </tr>
                </thead>
                <tbody>
                <c:forEach items="${addrInstanceList}" var="addrInstance" varStatus="status">
                    <tr>
                        <td>${status.index + 1}</td>
                        <td>${addrInstance['addr']}</td>
                        <td>${addrInstance['size']}</td>
                        <td>
                            <c:forEach items="${addrInstance['flags']}" var="clientType">
                                ${clientType}
                                <br/>
                            </c:forEach>
                        </td>
                        <td>
                            <button type="button" class="btn btn-success" data-target="#modal-${status.index}"
                                    data-toggle="modal">
                                查看实例连接统计
                            </button>

                            <div id="modal-${status.index}" class="modal fade" tabindex="-1">
                                <div class="modal-dialog" style="width: max-content">
                                    <div class="modal-content">
                                        <div class="modal-header">
                                            <button type="button" class="close" data-dismiss="modal"
                                                    aria-hidden="true"></button>
                                            <h4 class="modal-title">客户端 ${addrInstance['addr']} 连接信息</h4>
                                        </div>

                                        <form class="form-horizontal form-bordered form-row-stripped">
                                            <div class="modal-body">
                                                <div class="row">
                                                    <!-- 控件开始 -->
                                                    <div class="col-md-12">
                                                        <table class="table table-bordered table-striped table-hover">
                                                            <thead>
                                                            <tr>
                                                                <td>实例id</td>
                                                                <td>实例</td>
                                                                <td>连接数</td>
                                                            </tr>
                                                            </thead>
                                                            <tbody>
                                                            <c:forEach items="${addrInstance['instanceClientStats']}" var="instance">
                                                                <c:set var="instanceId" value="${instance.key}"></c:set>
                                                                <tr>
                                                                    <td>${instanceId}</td>
                                                                    <td><a href="/admin/instance/index?instanceId=${instanceId}&tabTag=instance_clientList" target="_blank">${instanceMap[instanceId]}</a></td>
                                                                    <td>${instance.value['count']}</td>
                                                                </tr>
                                                            </c:forEach>
                                                            </tbody>
                                                        </table>
                                                    </div>
                                                </div>
                                            </div>

                                            <div class="modal-footer">
                                                <button type="button" data-dismiss="modal" class="btn">Close</button>
                                            </div>
                                        </form>
                                    </div>
                                </div>
                            </div>
                        </td>
                    </tr>
                </c:forEach>
                </tbody>
            </table>
        </div>
    </div>
</div>

<script type="text/javascript">
    function changeCondition(value) {
        console.log('radio:'+value);
        $('#condition').val(value);
        $('#conditionFrom').submit();
    }
</script>

cachecloud-web/src/main/webapp/WEB-INF/jsp/app/appCommand.jsp
<%@ page contentType="text/html;charset=UTF-8" language="java" %>
<div class="row">
    <div id="console" class="console"></div>
    <script type="text/javascript">
        $(document).ready(function () {
            var console = $('#console');
            var controller = console.console({
                promptLabel: 'appId:${appId}> ',
                commandValidate: function (line) {
                    if (line == "") return false;
                    else return true;
                },
                commandHandle: function (line,report) {
                    $.ajax({
                        url: "/admin/app/commandExecute.json",
                        data: {appId: $('#appId').val(), command: line},
                        dataType: "json",
                        success: function (result) {
                            report([
                                {msg: result.result,
                                    className: "jquery-console-message-value"}
                            ]);
                        }
                    });
                },
                autofocus: true,
                animateScroll: true,
                promptHistory: true
            });
        });
    </script>
    <center><h4><font color='red'>注意：非测试应用只可以执行只读命令，如有需要清理数据请联系管理员！</font></h4></center>

    <input type="hidden" id="appId" value="${appId}">

</div>

cachecloud-web/src/main/webapp/WEB-INF/jsp/app/appDaily.jsp
<%@ page contentType="text/html;charset=UTF-8" language="java" %>
<%@ include file="/WEB-INF/jsp/manage/commons/taglibs.jsp"%>

<div class="container">

	<br/>
    <form method="get" action="/admin/app/index">
		<div class="row">
			<div style="float:right">
				<label style="font-weight:bold;text-align:left;">
				 	&nbsp;日期:&nbsp;&nbsp;
				</label>
				<input type="text" size="21" name="dailyDate" id="dailyDate" value="${dailyDate}" onFocus="WdatePicker({startDate:'%y-%M-01',dateFmt:'yyyy-MM-dd',alwaysUseStartDate:true})"/>
				
				<input type="hidden" name="appId" value="${appDesc.appId}">
				<input type="hidden" name="tabTag" value="app_daily">
				<label>&nbsp;<input type="submit" class="btn-4" value="查询"/></label>
			</div>
		</div>
	</form>


    <div class="row">
        <div class="page-header">
            <h4>客户端相关</h4> 
        </div>
        <table class="table table-striped table-hover">
            <tbody>
             <tr>
                 <td>客户端值分布(全天)</td>
                 <td>${appDailyData.valueSizeDistributeCountDescHtml}</td>
                 <td>客户端异常个数(全天)</td>
                 <td>${appDailyData.clientExceptionCount}</td>
                 <td>客户端连接数(每分钟)</td>
                 <td>
                  最大值:${appDailyData.maxMinuteClientCount} <br/>
                     平均值:${appDailyData.avgMinuteClientCount}
                 </td>
             </tr>
			 <tr>
				 <td>命令调用统计(全天):</td>
				 <td>
					 次数:${appDailyData.clientCmdCount}<br/>
					 平均耗时(ms):${appDailyData.clientAvgCmdCost}
				 </td>
				 <td>连接异常统计(全天)：</td>
				 <td>
					 次数:${appDailyData.clientConnExpCount}<br/>
					 平均耗时(ms):${appDailyData.clientAvgConnExpCost}
				 </td>
				 <td>命令超时统计(每分钟)：</td>
				 <td>
					 次数:${appDailyData.clientCmdExpCount} <br/>
					 平均耗时(ms):${appDailyData.clientAvgCmdExpCost}
				 </td>
			 </tr>
            </tbody>
        </table>
    </div>
    
    <div class="row">
        <div class="page-header">
            <h4>服务端相关</h4> 
        </div>
        <table class="table table-striped table-hover">
            <tbody>
	             <tr>
	                 <td>慢查询个数(全天)</td>
	                 <td>${appDailyData.slowLogCount}</td>
	                 <td>命令次数(每分钟)</td>
	                 <td>
	                 	最大值:${appDailyData.maxMinuteCommandCount} <br/>
	                    平均值:${appDailyData.avgMinuteCommandCount}
	                 </td>
	                 <td>命中率(每分钟)</td>
	                 <td>
	                  	最大值:${appDailyData.maxMinuteHitRatio}% <br/>
	                    最小值:${appDailyData.minMinuteHitRatio}% <br/>
	                    平均值:${appDailyData.avgHitRatio}%
	                 </td>
	             </tr>
	             
	             <tr>
	                 <td>内存使用量(全天)</td>
	                 <td>
	                 	平均使用量:${appDailyData.avgUsedMemory} M<br/>
                        最大使用量:${appDailyData.maxUsedMemory} M
	                 </td>
	                 <td>过期键数(全天)</td>
	                 <td>
	                 	${appDailyData.expiredKeysCount}
	                 </td>
	                 <td>剔除键数(全天)</td>
	                 <td>
	                  	${appDailyData.evictedKeysCount}
	                 </td>
	             </tr>
	             
	             
	             <tr>
	                 <td>键个数(全天)</td>
	                 <td>
	                 	平均值:${appDailyData.avgObjectSize}<br/>
                        最大值:${appDailyData.maxObjectSize}
	                 </td>
	                 <td>input流量(每分钟)</td>
	                 <td>
	                 	平均值:${appDailyData.avgMinuteNetInputByte} M<br/>
                       	 最大值:${appDailyData.maxMinuteNetInputByte} M
	                 </td>
	                 <td>output流量(每分钟)</td>
	                 <td>
	                  	 平均:${appDailyData.avgMinuteNetOutputByte} M<br/>
                       	 最大:${appDailyData.maxMinuteNetOutputByte} M<br/>
	                 </td>
	             </tr>
	             
            </tbody>
        </table>
    </div>
    
    
    <br/><br/><br/>
</div>

cachecloud-web/src/main/webapp/WEB-INF/jsp/app/appScaleApply.jsp
<%@ page language="java" contentType="text/html; charset=UTF-8" pageEncoding="UTF-8"%>
<%@ include file="/WEB-INF/jsp/manage/commons/taglibs.jsp"%>
<c:forEach items="${apps}" var="item">
	<div id="appScaleApply${item.appId}" class="modal fade" tabindex="-1" data-width="400">
		<div class="modal-dialog">
			<div class="modal-content">
			
				<div class="modal-header">
					<button type="button" class="close" data-dismiss="modal" aria-hidden="true"></button>
					<h4 class="modal-title">申请扩容</h4>
				</div>
				
				<form class="form-horizontal form-bordered form-row-stripped">
					<div class="modal-body">
						<div class="row">
							<!-- 控件开始 -->
							<div class="col-md-12">
								<!-- form-body开始 -->
								<div class="form-body">
									
									<div class="form-group">
										<label class="control-label col-md-3">
											每个分片容量:
										</label>
										<div class="col-md-5">
											<input type="text" name="memSize" id="memSize${item.appId}"
												value="${memSize}"  placeholder="每个分片容量"
												class="form-control" />
											<span class="help-block">
												追加的单位容量（256，512，1024）
											</span>
										</div>
									</div>
									<input type="hidden" id="appId" name="appId" value="${item.appId}"/>
								</div>
								<!-- form-body 结束 -->
							</div>
							<div id="info${item.appId}"></div>
							<!-- 控件结束 -->
						</div>
					</div>
					
					<div class="modal-footer">
						<button type="button" data-dismiss="modal" class="btn" >Close</button>
						<button type="button" class="btn red" onclick="appScaleApply('${item.appId}')">Ok</button>
					</div>
				
				</form>
			</div>
		</div>
	</div>
</c:forEach>

cachecloud-web/src/main/webapp/WEB-INF/jsp/app/appTopology.jsp
<%@ page contentType="text/html;charset=UTF-8" language="java" %>
<%@ include file="/WEB-INF/jsp/manage/commons/taglibs.jsp"%>

<div class="row">
    <div class="page-header">
        <h4>应用拓扑结构-<a href="/admin/app/index?appId=${appDesc.appId}">${appDesc.name}</a></h4>
    </div>
    <div style="margin-top: 20px">
        <table class="table table-bordered table-striped table-hover">
            <thead>
            <tr>
                <td>ID</td>
                <td>实例</td>
                <td>实例状态</td>
                <td>内存使用</td>
                <td>对象数</td>
                <td>连接数</td>
                <td>命中率</td>
                <td>碎片率</td>
                <td>角色</td>
                <td>主实例ID</td>
            </tr>
            </thead>
            <tbody>
            <c:forEach var="instance" items="${instanceList}" varStatus="status">
            	<c:set var="instanceStatsMapKey" value="${instance.ip}:${instance.port}"></c:set>
                <tr>
                    <c:if test="${instance.status==1 || instance.status==0}">
                    <td>
                    	 <a href="/admin/instance/index?instanceId=${instance.id}" target="_blank">${instance.id}</a>
                    	 <c:if test="${instance.masterInstanceId == 0 && instance.status != 2}">
							<span class="glyphicon glyphicon-star"></span>	                         
	                     </c:if>
                    </td>
                    <td><a href="/server/index?ip=${instance.ip}" target="_blank">${instance.ip}</a>:${instance.port}</td>
                    <td>${instance.statusDesc}</td>
					<td>
						<c:choose>
							<c:when test="${(instanceStatsMap[instanceStatsMapKey]).memUsePercent >= 80}">
								<c:set var="progressBarStatus" value="progress-bar-danger"/>
							</c:when>
							<c:otherwise>
								<c:set var="progressBarStatus" value="progress-bar-success"/>
							</c:otherwise>
						</c:choose>
					
                         <div class="progress margin-custom-bottom0">
                               <div class="progress-bar ${progressBarStatus}"
                                    role="progressbar"
                                    aria-valuenow="${(instanceStatsMap[instanceStatsMapKey]).memUsePercent}"
                                    aria-valuemax="100"
                                    aria-valuemin="0"
                                    style="width: ${(instanceStatsMap[instanceStatsMapKey]).memUsePercent}%">
                                    
	                               	<label style="color: #000000">
	                                   <fmt:formatNumber value="${(instanceStatsMap[instanceStatsMapKey]).usedMemory / 1024 / 1024 / 1024}" pattern="0.00"/>G&nbsp;&nbsp;Used/<fmt:formatNumber value="${(instanceStatsMap[instanceStatsMapKey]).maxMemory / 1024 / 1024 / 1024}" pattern="0.00"/>G&nbsp;&nbsp;Total
	                               	</label>
                                </div>
                         </div>
                  </td>
                  <td>
                  ${(instanceStatsMap[instanceStatsMapKey]).currItems}
                  </td>
                  <td>
                      <a href="/admin/instance/index?instanceId=${instance.id}&tabTag=instance_clientList" target="_blank">
                          ${(instanceStatsMap[instanceStatsMapKey]).currConnections}
                      </a>
                  </td>
                  <td>${(instanceStatsMap[instanceStatsMapKey]).hitPercent}</td>
                  <td>
	                  <c:set var="memFragmentationRatio" value="${(instanceStatsMap[instanceStatsMapKey]).memFragmentationRatio}"/>
	                  <c:choose>
	                		<c:when test="${memFragmentationRatio > 5 && (instanceStatsMap[instanceStatsMapKey]).usedMemory > 1024 * 1024 * 100}">
	                			  <c:set var="memFragmentationRatioLabel" value="label-danger"/>
	                		</c:when>
	                		<c:when test="${memFragmentationRatio >= 3 && memFragmentationRatio < 5 && (instanceStatsMap[instanceStatsMapKey]).usedMemory > 1024 * 1024 * 100}">
	                			  <c:set var="memFragmentationRatioLabel" value="label-warning"/>
	                		</c:when>
	                		<c:otherwise>
	                			  <c:set var="memFragmentationRatioLabel" value="label-success"/>
	                 		</c:otherwise>
	                  </c:choose>
	                  <label class="label ${memFragmentationRatioLabel}">${memFragmentationRatio}</label>
                  </td>
                  <td>${instance.roleDesc}</td>
                  <c:choose>
                     <c:when test="${instance.masterInstanceId >0}">
                         <td>
                             <a href="/admin/instance/index?instanceId=${instance.masterInstanceId}" target="_blank">${instance.masterInstanceId}</a>
                         </td>
                     </c:when>
                     <c:otherwise>
                         <td></td>
                     </c:otherwise>
                 </c:choose>
                 </c:if>
                </tr>
            </c:forEach>
            </tbody>
        </table>
    </div>
</div>