cachecloud-web/src/main/java/com/sohu/cache/entity/AppAudit.java
package com.sohu.cache.entity;

import com.sohu.cache.constant.AppAuditType;
import lombok.Data;

import java.text.SimpleDateFormat;
import java.util.Date;

/**
 * Created by yijunzhang
 */
@Data
public class AppAudit {

    private long id;

    private long appId;

    private long userId;

    private long operateId;

    private String userName;

    /**
     * 申请类型:AppAuditType
     */
    private int type;

    /**
     * 预留参数1
     */
    private String param1;
    /**
     * 预留参数2
     */
    private String param2;
    /**
     * 预留参数3
     */
    private String param3;

    /**
     * 申请描述
     */
    private String info;

    /**
     * 0:等待审批; 1:审批通过; -1:驳回
     */
    private int status;

    private Date createTime;

    private Date modifyTime;

    /**
     * 驳回原因
     */
    private String refuseReason;

    /**
     * 任务ID
     */
    private long taskId;

    private AppDesc appDesc;

    private AppAuditLog appAuditLog;

    public Date getCreateTime() {
        if (createTime != null) {
            return (Date) createTime.clone();
        }
        return null;
    }

    public void setCreateTime(Date createTime) {
        this.createTime = (Date) createTime.clone();
    }

    public Date getModifyTime() {
        if (modifyTime == null) {
            return null;
        }
        return (Date) modifyTime.clone();
    }

    public void setModifyTime(Date modifyTime) {
        this.modifyTime = (Date) modifyTime.clone();
    }

    public String getTypeDesc() {
        if (AppAuditType.getAppAuditType(type) != null) {
            return AppAuditType.getAppAuditType(type).getInfo();
        }
        return "";
    }

    public String getStatusDesc() {
        //        0:等待审批; 1:审批通过; -1:驳回
        if (status == 0) {
            return "等待审批";
        } else if (status == 1) {
            return "审批通过";
        } else if (status == -1) {
            return "驳回";
        } else {
            return status + "";
        }
    }

    public String getCreateTimeFormat() {
        SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd HH:mm:ss");
        if (createTime != null) {
            return sdf.format(createTime);
        }
        return "";
    }

}

cachecloud-web/src/main/java/com/sohu/cache/entity/AppDailyData.java
package com.sohu.cache.entity;

import com.sohu.cache.web.vo.AppDetailVO;
import lombok.Data;
import org.apache.commons.collections.MapUtils;

import java.util.Date;
import java.util.Map;

/**
 * 应用日报数据
 *
 * @author leifu
 */
@Data
public class AppDailyData {

    /**
     * 应用id
     */
    private long appId;

    /**
     * 开始日期
     */
    private Date startDate;

    /**
     * 结束日期
     */
    private Date endDate;

    /**
     * 日期
     */
    private Date date;

    /**
     * bigkey次数
     */
    private long bigKeyTimes;

    /**
     * bigkey信息
     */
    private String bigKeyInfo;

    /**
     * 慢查询次数
     */
    private long slowLogCount;

    /**
     * 延迟事件个数
     */
    private long latencyCount;

    /**
     * 客户端异常个数
     */
    private long clientExceptionCount;
    /**
     * 累计命令调用次数
     */
    private long clientCmdCount;
    /**
     * 平均命令调用耗时
     */
    private double clientAvgCmdCost;
    /**
     * 累计连接异常事件次数
     */
    private long clientConnExpCount;
    /**
     * 平均连接异常事件耗时
     */
    private double clientAvgConnExpCost;
    /**
     * 累计命令超时事件次数
     */
    private long clientCmdExpCount;
    /**
     * 平均命令超时事件耗时
     */
    private double clientAvgCmdExpCost;

    /**
     * 每分钟最大客户端连接数
     */
    private long maxMinuteClientCount;

    /**
     * 每分钟平均客户端连接数
     */
    private long avgMinuteClientCount;

    /**
     * 每分钟最大命令数
     */
    private long maxMinuteCommandCount;

    /**
     * 每分钟平均命令数
     */
    private long avgMinuteCommandCount;

    /**
     * 平均命中率
     */
    private double avgHitRatio;

    /**
     * 每分钟最小命中率
     */
    private double minMinuteHitRatio;

    /**
     * 每分钟最大命中率
     */
    private double maxMinuteHitRatio;

    /**
     * 平均内存使用量
     */
    private long avgUsedMemory;

    /**
     * 最大内存使用量
     */
    private long maxUsedMemory;

    /**
     * 过期键个数
     */
    private long expiredKeysCount;

    /**
     * 剔除键个数
     */
    private long evictedKeysCount;

    /**
     * 每分钟平均网络input量
     */
    private double avgMinuteNetInputByte;

    /**
     * 每分钟最大网络input量
     */
    private double maxMinuteNetInputByte;

    /**
     * 每分钟平均网络output量
     */
    private double avgMinuteNetOutputByte;

    /**
     * 每分钟最大网络output量
     */
    private double maxMinuteNetOutputByte;

    /**
     * 键个数平均值
     */
    private long avgObjectSize;

    /**
     * 键个数最大值
     */
    private long maxObjectSize;

    /**
     * 值分布
     */
    private Map<String, Long> valueSizeDistributeCountMap;

    /**
     * 应用详情
     */
    private AppDetailVO appDetailVO;

    public String getValueSizeDistributeCountDesc() {
        if (MapUtils.isEmpty(valueSizeDistributeCountMap)) {
            return "无";
        }
        StringBuffer desc = new StringBuffer();
        for (Map.Entry<String, Long> entry : valueSizeDistributeCountMap.entrySet()) {
            desc.append(entry.getKey()).append(":").append(entry.getValue()).append("次<br/>");
        }
        return desc.toString();
    }

    public String getValueSizeDistributeCountDescHtml() {
        return bigKeyInfo.replace("\n", "<br/>").replace(":", ":\t");
    }
}

cachecloud-web/src/main/resources/templates/OperationAlert.ftl
<!DOCTYPE html>
<head>
    <meta charset=UTF-8/>
    <title>CacheCloud运维操作通知</title>
</head>
<body>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8">
<p>
<table style="width:100%; font-size:12px;" width="100%" cellpadding="0" cellspacing="0">
    <colgroup>
        <col style="width: 5px;">
    </colgroup>
    <tr>
        <td></td>
        <td style="padding-top:20px; padding-left:27px;">
            <ul>
                <li><span style="font-weight: bold; padding-top:20px; color:#3f3f3f;">运维操作机器通知：</span></li>
            </ul>
            <table style="table-layout:fixed;width: 872px;border-collapse: collapse;word-break: break-all;word-wrap:break-word;border-top: 1px dotted #676767;text-align: center;color: #000; font-family:'宋体'; font-size:12px; margin-top:10px; margin-left: 24px">
                <tr>
                    <td style="border-right: 1px dotted #676767; border-bottom: 1px dotted #676767; height:33px; width: 50px;">
                        机器ip
                    </td>
                    <td style="border-right: 1px dotted #676767; border-bottom: 1px dotted #676767; height:33px; width: 50px;">
                        宿主机ip
                    </td>
                    <td style="border-right: 1px dotted #676767; border-bottom: 1px dotted #676767; height:33px; width: 50px;">
                        机器详情
                    </td>
                    <td style="border-right: 1px dotted #676767; border-bottom: 1px dotted #676767; height:33px; width: 50px;">
                        操作
                    </td>
                    <td style="border-right: 1px dotted #676767; border-bottom: 1px dotted #676767; height:33px; width: 50px;">
                        Status
                    </td>
                    <td style="border-right: 1px dotted #676767; border-bottom: 1px dotted #676767; height:33px; width: 50px;">
                        Message
                    </td>
                </tr>
                <#list operationAlertValueResultList as item>
                    <tr>
                        <td style="border-right: 1px dotted #676767; border-bottom: 1px dotted #676767; height:33px; width: 50px;">
                            ${item.ip!}
                        </td>
                        <td style="border-right: 1px dotted #676767; border-bottom: 1px dotted #676767; height:33px; width: 50px;">
                            <#if item.machineInfo??>
                                ${item.machineInfo.realIp!}
                            </#if>
                        </td>
                        <td style="border-right: 1px dotted #676767; border-bottom: 1px dotted #676767; height:33px; width: 50px;">
                            <#if item.machineInfo??>
                                内存：${item.machineInfo.mem!} G<br/>
                                cpu：${item.machineInfo.cpu!}<br/>
                                备注说明：${item.machineInfo.extraDesc!}
                            </#if>
                        </td>
                        <td style="border-right: 1px dotted #676767; border-bottom: 1px dotted #676767; height:33px; width: 50px;">
                            ${item.type!}
                        </td>
                        <td style="border-right: 1px dotted #676767; border-bottom: 1px dotted #676767; height:33px; width: 50px;">
                            ${item.status!}
                        </td>
                        <td style="border-right: 1px dotted #676767; border-bottom: 1px dotted #676767; height:33px; width: 50px;">
                            ${item.message!}
                        </td>
                    </tr>
                </#list>

            </table>
        </td>
    </tr>

</table>
</p>
</body>
</html>

cachecloud-web/src/main/resources/templates/appAudit.ftl
<!DOCTYPE html>
<head>
    <meta charset=UTF-8/>
    <title>CacheCloud审核邮件</title>
</head>
<body>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8">
<p>
<table style="width:100%; font-size:12px;" width="100%" cellpadding="0" cellspacing="0">
    <colgroup>
        <col style="width: 5px;">
    </colgroup>
    <tr>
        <td style="width:5px;"></td>
        <td style="color:#3f3f3f; font-weight: bold;font-size:12px; font-family: '宋体'; padding: 5px 0 15px 0">
            ${appAudit.userName!}，您好，欢迎使用CacheCloud平台，您的申请处理进度如下：
        </td>
    </tr>
    <tr>
        <td></td>
        <td style="padding-top:20px; padding-left:27px;">
            <ul>
                <li><span style="font-weight: bold; padding-top:20px; color:#3f3f3f;">申请处理信息：</span></li>
            </ul>
            <table style="table-layout:fixed;width: 872px;border-collapse: collapse;word-break: break-all;word-wrap:break-word;border-top: 1px dotted #676767;text-align: center;color: #000; font-family:'宋体'; font-size:12px; margin-top:10px; margin-left: 24px">
                <tr>
                    <td style="border-right: 1px dotted #676767; border-bottom: 1px dotted #676767;text-align: left; height:33px; width: 50px;">
                        申请类型：
                    </td>
                    <td style="border-right: 1px dotted #676767; border-bottom: 1px dotted #676767; height:33px; width: 140px;">
                        ${appAudit.typeDesc!}
                    </td>
                    <td style="border-right: 1px dotted #676767; border-bottom: 1px dotted #676767; text-align: left;height:33px; width: 50px;">
                        申请描述：
                    </td>
                    <td style="border-right: 1px dotted #676767; border-bottom: 1px dotted #676767; height:33px; width: 140px;">
                        ${appAudit.info!}
                    </td>
                    <td style="border-right: 1px dotted #676767; border-bottom: 1px dotted #676767; text-align: left;height:33px; width: 50px;">
                        申请时间：
                    </td>
                    <td style="border-right: 1px dotted #676767; border-bottom: 1px dotted #676767; height:33px; width: 140px;">
                        ${appAudit.createTimeFormat!}
                    </td>
                </tr>
                <tr>
                    <td style="border-right: 1px dotted #676767; border-bottom: 1px dotted #676767;text-align: left; height:33px; width: 50px;">
                        处理状态：
                    </td>
                    <td style="border-right: 1px dotted #676767; border-bottom: 1px dotted #676767; height:33px; width: 140px; color: red;">
                        ${appAudit.statusDesc!}
                    </td>
                    <td style="border-right: 1px dotted #676767; border-bottom: 1px dotted #676767;text-align: left; height:33px; width: 50px;">
                        处理描述：
                    </td>
                    <td style="border-right: 1px dotted #676767; border-bottom: 1px dotted #676767; height:33px; width: 140px; color: red;">
                        ${appAudit.refuseReason!}
                    </td>
                    <td style="border-right: 1px dotted #676767; border-bottom: 1px dotted #676767;text-align: left; height:33px; width: 50px;">
                        处理时间：
                    </td>
                    <td style="border-right: 1px dotted #676767; border-bottom: 1px dotted #676767; height:33px; width: 140px;">
                        ${appAudit.modifyTime?string("yyyy-MM-dd HH:mm:ss")!}
                    </td>
                </tr>
            </table>
            <br/>
            <ul>
                <li><span style="font-weight: bold; padding-top:20px; color:#3f3f3f;">应用详细信息：</span></li>
            </ul>
            <table style="table-layout:fixed;width: 872px;border-collapse: collapse;word-break: break-all;word-wrap:break-word;border-top: 1px dotted #676767;text-align: center;color: #000; font-family:'宋体'; font-size:12px; margin-top:10px; margin-left: 24px">
                <tr>
                    <td style="border-right: 1px dotted #676767; border-bottom: 1px dotted #676767;text-align: left; height:33px; width: 50px;">
                        应用名称：
                    </td>
                    <td style="border-right: 1px dotted #676767; border-bottom: 1px dotted #676767; height:33px; width: 140px;">
                        ${appDesc.name!}
                    </td>
                    <td style="border-right: 1px dotted #676767; border-bottom: 1px dotted #676767;text-align: left; height:33px; width: 50px;">
                        应用类型：
                    </td>
                    <td style="border-right: 1px dotted #676767; border-bottom: 1px dotted #676767; height:33px; width: 140px;">
                        ${appDesc.typeDesc!}
                    </td>
                    <td style="border-right: 1px dotted #676767; border-bottom: 1px dotted #676767;text-align: left; height:33px; width: 50px;">
                        应用状态：
                    </td>
                    <td style="border-right: 1px dotted #676767; border-bottom: 1px dotted #676767; height:33px; width: 140px; color: red;">
                        ${appDesc.statusDesc!}
                    </td>
                </tr>
                <tr>
                    <td style="border-right: 1px dotted #676767; border-bottom: 1px dotted #676767;text-align: left; height:33px; width: 50px;">
                        是否测试：
                    </td>
                    <td style="border-right: 1px dotted #676767; border-bottom: 1px dotted #676767; height:33px; width: 140px;">
                        <#if appDesc.isTest == 1>
                            是
                        <#else>
                            否
                        </#if>
                    </td>
                    <td style="border-right: 1px dotted #676767; border-bottom: 1px dotted #676767;text-align: left; height:33px; width: 50px;">
                        是否持久化：
                    </td>
                    <td style="border-right: 1px dotted #676767; border-bottom: 1px dotted #676767; height:33px; width: 140px;">
                        <#if appDesc.needPersistence == 1>
                            是
                        <#else>
                            否
                        </#if>
                    </td>
                    <td style="border-right: 1px dotted #676767; border-bottom: 1px dotted #676767;text-align: left; height:33px; width: 50px;">
                        是否有后端数据源：
                    </td>
                    <td style="border-right: 1px dotted #676767; border-bottom: 1px dotted #676767; height:33px; width: 140px;">
                        <#if appDesc.hasBackStore == 1>
                            是
                        <#else>
                            否
                        </#if>
                    </td>
                </tr>
                <tr>
                    <td style="border-right: 1px dotted #676767; border-bottom: 1px dotted #676767;text-align: left; height:33px; width: 50px;">
                        应用描述：
                    </td>
                    <td style="border-right: 1px dotted #676767; border-bottom: 1px dotted #676767; height:33px; width: 140px;">
                        ${appDesc.intro!}
                    </td>
                    <td style="border-right: 1px dotted #676767; border-bottom: 1px dotted #676767;text-align: left; height:33px; width: 50px;">
                        应用负责人：
                    </td>
                    <td style="border-right: 1px dotted #676767; border-bottom: 1px dotted #676767; height:33px; width: 140px;">
                        ${appDesc.officer!}
                    </td>
                    <td style="border-right: 1px dotted #676767; border-bottom: 1px dotted #676767;text-align: left; height:33px; width: 50px;">
                        应用申请时间：
                    </td>
                    <td style="border-right: 1px dotted #676767; border-bottom: 1px dotted #676767; height:33px; width: 140px;">
                        ${appDesc.createTime?string("yyyy-MM-dd HH:mm:ss")!}
                    </td>
                </tr>
            </table>
        </td>
    </tr>

</table>
</p>
</body>
</html>

cachecloud-web/src/main/resources/templates/appDaily.ftl
<!DOCTYPE html>
<head>
    <meta charset=UTF-8/>
    <title>CacheCloud应用日报</title>
</head>
<body>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8">
<p>
<table style="width:100%; font-size:12px;" width="100%" cellpadding="0" cellspacing="0">
    <colgroup>
        <col style="width: 5px;">
    </colgroup>
    <tr>
        <td></td>
        <td style="padding-top:20px; padding-left:27px;">
        	<ul>
                <li><span style="font-weight: bold; padding-top:20px; color:#3f3f3f;">应用详细信息：${appDesc.appId?c}</span></li>
            </ul>
            <table style="table-layout:fixed;width: 872px;border-collapse: collapse;word-break: break-all;word-wrap:break-word;border-top: 1px dotted #676767;text-align: center;color: #000; font-family:'宋体'; font-size:12px; margin-top:10px; margin-left: 24px">
                <tr>
                    <td style="border-right: 1px dotted #676767; border-bottom: 1px dotted #676767;text-align: left; height:33px; width: 50px;">
                        应用名称：
                    </td>
                    <td style="border-right: 1px dotted #676767; border-bottom: 1px dotted #676767; height:33px; width: 140px;">
                        ${appDesc.name!}
                    </td>
                    <td style="border-right: 1px dotted #676767; border-bottom: 1px dotted #676767;text-align: left; height:33px; width: 50px;">
                        应用类型：
                    </td>
                    <td style="border-right: 1px dotted #676767; border-bottom: 1px dotted #676767; height:33px; width: 140px;">
                        ${appDesc.typeDesc!}
                    </td>
                    <td style="border-right: 1px dotted #676767; border-bottom: 1px dotted #676767;text-align: left; height:33px; width: 50px;">
                        应用状态：
                    </td>
                    <td style="border-right: 1px dotted #676767; border-bottom: 1px dotted #676767; height:33px; width: 140px;">
                        ${appDesc.statusDesc!}
                    </td>
                </tr>
                <tr>
                    <td style="border-right: 1px dotted #676767; border-bottom: 1px dotted #676767;text-align: left; height:33px; width: 50px;">
                        应用描述：
                    </td>
                    <td style="border-right: 1px dotted #676767; border-bottom: 1px dotted #676767; height:33px; width: 140px;">
                        ${appDesc.intro!}
                    </td>
                    <td style="border-right: 1px dotted #676767; border-bottom: 1px dotted #676767;text-align: left; height:33px; width: 50px;">
                        应用负责人：
                    </td>
                    <td style="border-right: 1px dotted #676767; border-bottom: 1px dotted #676767; height:33px; width: 140px;">
                        ${appDesc.officer!}
                    </td>
                    <td style="border-right: 1px dotted #676767; border-bottom: 1px dotted #676767;text-align: left; height:33px; width: 50px;">
                        应用申请时间：
                    </td>
                    <td style="border-right: 1px dotted #676767; border-bottom: 1px dotted #676767; height:33px; width: 140px;">
                        ${appDesc.createTime?string("yyyy-MM-dd HH:mm:ss")!}
                    </td>
                </tr>
            </table>
        
            <ul>
                <li><span style="font-weight: bold; padding-top:20px; color:#3f3f3f;">客户端相关(确保使用有客户端统计的版本):</span></li>
            </ul>
            <table style="table-layout:fixed;width: 872px;border-collapse: collapse;word-break: break-all;word-wrap:break-word;border-top: 1px dotted #676767;text-align: center;color: #000; font-family:'宋体'; font-size:12px; margin-top:10px; margin-left: 24px">
                <tr>
                    <td style="border-right: 1px dotted #676767; border-bottom: 1px dotted #676767;text-align: left; height:33px; width: 50px;">
                        客户端值分布(全天):
                    </td>
                    <td style="border-right: 1px dotted #676767; border-bottom: 1px dotted #676767; height:33px; width: 140px;">
						${appDailyData.valueSizeDistributeCountDesc!}
                    </td>
                    <td style="border-right: 1px dotted #676767; border-bottom: 1px dotted #676767; text-align: left;height:33px; width: 50px;">
                        客户端连接数(每分钟)：
                    </td>
                    <td style="border-right: 1px dotted #676767; border-bottom: 1px dotted #676767; height:33px; width: 140px;">
                        最大值:${appDailyData.maxMinuteClientCount!} <br/>
                        平均值:${appDailyData.avgMinuteClientCount!}
                    </td>
                    <td style="border-right: 1px dotted #676767; border-bottom: 1px dotted #676767; text-align: left;height:33px; width: 50px;">
                        客户端延迟事件数(全天)：
                    </td>
                    <td style="border-right: 1px dotted #676767; border-bottom: 1px dotted #676767; height:33px; width: 140px;">
                        ${appDailyData.latencyCount!}
                    </td>
                </tr>
                <tr>
                    <td style="border-right: 1px dotted #676767; border-bottom: 1px dotted #676767;text-align: left; height:33px; width: 50px;">
                        命令调用统计(全天):
                    </td>
                    <td style="border-right: 1px dotted #676767; border-bottom: 1px dotted #676767; height:33px; width: 140px;">
                        次数:${appDailyData.clientCmdCount!}<br/>
                        平均耗时(ms):${appDailyData.clientAvgCmdCost!}
                    </td>
                    <td style="border-right: 1px dotted #676767; border-bottom: 1px dotted #676767; text-align: left;height:33px; width: 50px;">
                        连接异常统计(全天)：
                    </td>
                    <td style="border-right: 1px dotted #676767; border-bottom: 1px dotted #676767; height:33px; width: 140px;">
                        次数:${appDailyData.clientConnExpCount!}<br/>
                        平均耗时(ms):${appDailyData.clientAvgConnExpCost!}
                    </td>
                    <td style="border-right: 1px dotted #676767; border-bottom: 1px dotted #676767; text-align: left;height:33px; width: 50px;">
                        命令超时统计(全天)：
                    </td>
                    <td style="border-right: 1px dotted #676767; border-bottom: 1px dotted #676767; height:33px; width: 140px;">
                        次数:${appDailyData.clientCmdExpCount!} <br/>
                        平均耗时(ms):${appDailyData.clientAvgCmdExpCost!}
                    </td>
                </tr>
            </table>
            <br/>
            
            <ul>
                <li><span style="font-weight: bold; padding-top:20px; color:#3f3f3f;">服务端相关:</span></li>
            </ul>
            <table style="table-layout:fixed;width: 872px;border-collapse: collapse;word-break: break-all;word-wrap:break-word;border-top: 1px dotted #676767;text-align: center;color: #000; font-family:'宋体'; font-size:12px; margin-top:10px; margin-left: 24px">
                <tr>
                    <td style="border-right: 1px dotted #676767; border-bottom: 1px dotted #676767;text-align: left; height:33px; width: 50px;">
                        慢查询个数(全天)：
                    </td>
                    <td style="border-right: 1px dotted #676767; border-bottom: 1px dotted #676767; height:33px; width: 140px;">
                        ${appDailyData.slowLogCount!}
                    </td>
					<td style="border-right: 1px dotted #676767; border-bottom: 1px dotted #676767;text-align: left; height:33px; width: 50px;">
                        命令次数(每分钟)：
                    </td>
                    <td style="border-right: 1px dotted #676767; border-bottom: 1px dotted #676767; height:33px; width: 140px;">
                       	 最大值:${appDailyData.maxMinuteCommandCount!} <br/>
                       	 平均值:${appDailyData.avgMinuteCommandCount!}
                    </td>
                    <td style="border-right: 1px dotted #676767; border-bottom: 1px dotted #676767;text-align: left; height:33px; width: 50px;">
                        命中率(每分钟)：
                    </td>
                    <td style="border-right: 1px dotted #676767; border-bottom: 1px dotted #676767; height:33px; width: 140px;">
                       	 最大值:${appDailyData.maxMinuteHitRatio!}% <br/>
                       	 最小值:${appDailyData.minMinuteHitRatio!}% <br/>
                       	 平均值:${appDailyData.avgHitRatio!}%
                    </td>
                </tr>
                
                <tr>
                    <td style="border-right: 1px dotted #676767; border-bottom: 1px dotted #676767;text-align: left; height:33px; width: 50px;">
                        内存使用量(全天)：
                    </td>
                    <td style="border-right: 1px dotted #676767; border-bottom: 1px dotted #676767; height:33px; width: 140px;">
                        平均使用量:${appDailyData.avgUsedMemory!} M<br/>
                        最大使用量:${appDailyData.maxUsedMemory!} M
                    </td>
					<td style="border-right: 1px dotted #676767; border-bottom: 1px dotted #676767;text-align: left; height:33px; width: 50px;">
                        过期键数(全天)：
                    </td>
                    <td style="border-right: 1px dotted #676767; border-bottom: 1px dotted #676767; height:33px; width: 140px;">
                       	 ${appDailyData.expiredKeysCount!}
                    </td>
                    <td style="border-right: 1px dotted #676767; border-bottom: 1px dotted #676767;text-align: left; height:33px; width: 50px;">
                        剔除键数(全天)：
                    </td>
                    <td style="border-right: 1px dotted #676767; border-bottom: 1px dotted #676767; height:33px; width: 140px;">
                       	 ${appDailyData.evictedKeysCount!}
                    </td>
                </tr>
                
                <tr>
                    <td style="border-right: 1px dotted #676767; border-bottom: 1px dotted #676767;text-align: left; height:33px; width: 50px;">
                       键个数(全天)：
                    </td>
                    <td style="border-right: 1px dotted #676767; border-bottom: 1px dotted #676767; height:33px; width: 140px;">
                        平均值:${appDailyData.avgObjectSize!}<br/>
                        最大值:${appDailyData.maxObjectSize!}
                    </td>
					<td style="border-right: 1px dotted #676767; border-bottom: 1px dotted #676767;text-align: left; height:33px; width: 50px;">
                        input流量(每分钟)：
                    </td>
                    <td style="border-right: 1px dotted #676767; border-bottom: 1px dotted #676767; height:33px; width: 140px;">
                       	 平均值:${appDailyData.avgMinuteNetInputByte!} M<br/>
                       	 最大值:${appDailyData.maxMinuteNetInputByte!} M<br/>
                    </td>
                    <td style="border-right: 1px dotted #676767; border-bottom: 1px dotted #676767;text-align: left; height:33px; width: 50px;">
                        output流量(每分钟)：
                    </td>
                    <td style="border-right: 1px dotted #676767; border-bottom: 1px dotted #676767; height:33px; width: 140px;">
                       	 平均:${appDailyData.avgMinuteNetOutputByte!} M<br/>
                       	 最大:${appDailyData.maxMinuteNetOutputByte!} M<br/>
                    </td>
                </tr>
            </table>
            <br/>
            
        </td>
    </tr>

</table>
</p>
</body>
</html>